/**
 * Copyright 2014 Atos
 * Contact: Atos <roman.sosa@atos.net>
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 02:24:14 PM BST 
//


package eu.modaclouds.sla.mediator.model.qosconstraints;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for range complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="range">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hasMaxValue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="hasMinValue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="inSet" type="{http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema}set" minOccurs="0"/>
 *         &lt;element name="outSet" type="{http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema}set" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "range", propOrder = {
    "hasMaxValue",
    "hasMinValue",
    "inSet",
    "outSet"
})
public class Range {

    protected Float hasMaxValue;
    protected Float hasMinValue;
    protected Set inSet;
    protected Set outSet;

    /**
     * Gets the value of the hasMaxValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getHasMaxValue() {
        return hasMaxValue;
    }

    /**
     * Sets the value of the hasMaxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setHasMaxValue(Float value) {
        this.hasMaxValue = value;
    }

    /**
     * Gets the value of the hasMinValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getHasMinValue() {
        return hasMinValue;
    }

    /**
     * Sets the value of the hasMinValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setHasMinValue(Float value) {
        this.hasMinValue = value;
    }

    /**
     * Gets the value of the inSet property.
     * 
     * @return
     *     possible object is
     *     {@link Set }
     *     
     */
    public Set getInSet() {
        return inSet;
    }

    /**
     * Sets the value of the inSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Set }
     *     
     */
    public void setInSet(Set value) {
        this.inSet = value;
    }

    /**
     * Gets the value of the outSet property.
     * 
     * @return
     *     possible object is
     *     {@link Set }
     *     
     */
    public Set getOutSet() {
        return outSet;
    }

    /**
     * Sets the value of the outSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Set }
     *     
     */
    public void setOutSet(Set value) {
        this.outSet = value;
    }

}
